org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.172
loader_version_range=[4,)

mod_id=mobtrinkets
mod_name=Mob Trinkets
mod_license=MIT
mod_version=1.0.0
mod_group_id=org.chubby.github.mobtrinkets
mod_description=Collect rare trinkets from mobs and gain their powers.
